const $=s=>document.querySelector(s);let map,markers=new Map(),refreshMs=15000;
function fmtDate(value){if(!value)return '—';return new Date(value).toLocaleString('fr-FR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
async function get(url){const r=await fetch(url);if(!r.ok)throw new Error(await r.text());return r.json()}
function initMap(){map=L.map('map',{worldCopyJump:true,zoomControl:true}).setView([25,10],2);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map)}
async function loadStats(){const s=await get('/api/stats');$('#totalAttempts').textContent=s.total_attempts.toLocaleString('fr-FR');$('#uniqueIps').textContent=s.unique_ips.toLocaleString('fr-FR');$('#commands').textContent=s.commands.toLocaleString('fr-FR');$('#uploads').textContent=s.malware_uploads.toLocaleString('fr-FR');$('#last24h').textContent=`${s.last_24h.toLocaleString('fr-FR')} sur 24h`}
async function loadSessions(){const data=await get('/api/recent-sessions');const body=$('#sessionsBody');if(!data.length){body.innerHTML='<tr><td colspan="4" class="empty">Aucune session. Vérifiez le chemin du log Cowrie.</td></tr>';return}body.innerHTML=data.map(s=>`<tr onclick="openSession('${encodeURIComponent(s.session)}')"><td>${s.src_ip}</td><td>${s.country||'Unknown'}</td><td>${fmtDate(s.last_seen)}</td><td>${s.event_count}</td></tr>`).join('')}
async function loadMap(){const data=await get('/api/map-points');data.forEach(p=>{const popup=`<b>${p.ip}</b><br>${p.country||'Unknown'} · ${p.count} événement(s)`;if(markers.has(p.ip)){markers.get(p.ip).setRadius(Math.min(16,5+Math.log(p.count+1)*3)).bindPopup(popup);return}const marker=L.circleMarker([p.lat,p.lon],{radius:Math.min(16,5+Math.log(p.count+1)*3),color:'#5ee7d2',fillColor:'#5ee7d2',fillOpacity:.75,weight:1}).addTo(map).bindPopup(popup);markers.set(p.ip,marker);marker.setStyle({color:'#ff9b5f',fillColor:'#ff9b5f'});setTimeout(()=>marker.setStyle({color:'#5ee7d2',fillColor:'#5ee7d2'}),650)})}
async function loadTimeline(){const data=await get('/api/timeline?hours=24');const max=Math.max(1,...data.map(x=>x.count));$('#timeline').innerHTML=data.map(x=>`<div class="bar" title="${x.bucket}: ${x.count}"><i style="height:${Math.max(3,x.count/max*145)}px"></i><small>${x.bucket.slice(11,13)}h</small></div>`).join('')||'<div class="empty">Pas encore de données</div>'}
async function loadTop(){const data=await get('/api/top-attackers');$('#topAttackers').innerHTML=(data.attackers||[]).map((x,i)=>`<li><span class="rank">${String(i+1).padStart(2,'0')}</span><span class="rank-ip">${x.label}</span><span class="rank-count">${x.count}</span></li>`).join('')||'<li class="empty">Aucune donnée</li>'}
async function refresh(){try{await Promise.all([loadStats(),loadSessions(),loadMap(),loadTimeline(),loadTop()]);$('#statusText').textContent='Flux actif';$('#lastRefresh').textContent=fmtDate(new Date());}catch(e){console.error(e);$('#statusText').textContent='API indisponible'}}
async function openSession(id){const data=await get('/api/sessions/'+id);$('#dialogTitle').textContent=`${data.session} · ${data.src_ip}`;$('#sessionDetail').innerHTML=`<div class="detail"><p class="eyebrow">${data.geo.country||'Unknown'} · ${data.events.length} ÉVÉNEMENTS</p>${data.events.map(e=>`<div class="event"><time>${fmtDate(e.timestamp)} · ${e.eventid||'event'}</time>${e.input?`<code>$ ${e.input}</code>`:`<code>${e.username||''} / ${e.password||''}</code>`}</div>`).join('')}</div>`;$('#sessionDialog').showModal()}
(async()=>{initMap();try{const c=await get('/api/config');refreshMs=(c.refresh_seconds||15)*1000;$('#refreshRate').textContent=c.refresh_seconds||15}catch(e){}await refresh();setInterval(refresh,refreshMs);$('#refreshButton').onclick=refresh})()
